export const textcontent = {
    en: {
        login: "Login",
        register: "Register",
        emailExample: "Email@example.com",
        passwordExample: "Password",
        tasks: "Tasks",
        months: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
        ],
    },
    fi: {
        login: "Kirjaudu sisään",
        register: "Rekisteröidy",
        emailExample: "Posti@esimerkki.com",
        passwordExample: "Salasana",
        tasks: "Tehtävät",
        months: [
            "Tammikuu",
            "Helmikuu",
            "Maaliskuu",
            "Huhtikuu",
            "Toukokuu",
            "Kesäkuu",
            "Heinäkuu",
            "Elokuu",
            "Syyskuu",
            "Lokakuu",
            "Marraskuu",
            "Joulukuu",
        ],
    },
    swe: {
        login: "Logga in",
        register: "Bli medlem",
        emailExample: "E-post@exampel.com",
        passwordExample: "Lösenord",
        tasks: "Uppgifter",
        months: [
            "Januari",
            "Februari",
            "Mars",
            "April",
            "Maj",
            "Juni",
            "Juli",
            "Augusti",
            "September",
            "Oktober",
            "November",
            "December",
        ],
    },
}